### PR TITLE
API server update for APD APIs

### PR DESCRIPTION
**Pull request by ThorodanBrom**
- Updated `ApiServerVerticle` with APD service and APD API handlers
- Added OpenAPI spec

### CODE REVIEW

**Comment by ThorodanBrom** [comment]
retest this please

**Comment by ThorodanBrom** [comment]
The last 2 Jenkins runs (iudx-aaa-server PR no. 59, 60) failed due to ZAP errors w.r.t. timestamp disclosure. Usually this happens with `/token` and `/token/introspect` - not sure why it's happening in the other APIs too. That too, the 'timestamps' disclosed in APIs except get token and introspect are not recent. [e.g.](https://jenkins.iudx.io/job/iudx%20aaa-server%20(PR)%20pipeline/60/zap/)

My guess is that a UUID probably has 8 digits in it's first part, and ZAP probably thinks it's a timestamp

**Comment by mahimatics** [comment]
@ThorodanBrom Is it just a matter of the number of low risk errors in the scan that's triggering the build failure? We can either look into removing that threshold for low risk issues, or we can solve one of the other ones to bring down the total number of them. I was thinking if just fixing that X-Content-Type-Options Header Missing problem will be enough for that, since the solution suggested seems fairly straightforward. Let me know what you think.

**Comment by ThorodanBrom** [comment]
> @ThorodanBrom Is it just a matter of the number of low risk errors in the scan that's triggering the build failure? We can either look into removing that threshold for low risk issues, or we can solve one of the other ones to bring down the total number of them. I was thinking if just fixing that X-Content-Type-Options Header Missing problem will be enough for that, since the solution suggested seems fairly straightforward. Let me know what you think.

Yeah, it's due to the crossing of the threshold set for low-risk errors. It's currently set to be 44 as per commit 90f110c1f8c6ac127d345a59947faa30a0ffd690 . 

I've noticed that the number of Unix timestamp disclosure errors are fluctuating across the different test runs, it's never constant. For example, [here](https://jenkins.iudx.io/job/iudx%20aaa-server%20(PR)%20pipeline/20/zap/) it's 25 and [here](https://jenkins.iudx.io/job/iudx%20aaa-server%20(PR)%20pipeline/58/zap/) it's 17. In the former, it claims to find timestamps in the GET /organizations API (the UUID having consecutive digits is the only reason I can think of). The X-Content-Type errors are constantly 22.

We can fix the X-Content-Type issue, but since the timestamp error instances are not constant, setting a threshold for it would be difficult. So we can either remove the low threshold completely by reverting 90f110c1f8c6ac127d345a59947faa30a0ffd690, or if possible, ignore that class of errors.

**Comment by mahimatics** [comment]
Okay. @karun-singh, could you please check if we can disable that particular error all together? The ZAP suggested solution is also something that we cannot automate, so this isn't a very helpful check.

**Comment by karun-singh** [comment]
Okay @mahimatics, will remove the Low-Alerts threshold all together.

**Pull request merged**
