### PR TITLE
Doc updates

### PR DESCRIPTION
**Pull request by ThorodanBrom**
- Updated GET, DELETE, POST /policies APIs with information about APD policies
- Updated POST /token API with information about APD tokens

### CODE REVIEW

**Comment by ThorodanBrom** [comment]
Some of the details added may or may not be required in this version of the docs.

**Comment by ThorodanBrom** [comment]
Also, I'm not sure how we will backport this commit to the v3.5 branch. Should I make a separate PR to merge to that branch?

**Comment by ThorodanBrom** [comment]
retest this please

**Comment by ThorodanBrom** [comment]
retest this please

**Comment by mahimatics** [comment]
> Also, I'm not sure how we will backport this commit to the v3.5 branch. Should I make a separate PR to merge to that branch?

No, I don't think that's required. As far as the open API docs are concerned, we usually just point everyone to the [live version](https://authorization.iudx.org.in/apis) anyway. So as long as that is updated, it's fine.

But if there are changes / bug fixes that need to be backported to v.3.5.0, then you can just make that PR to that branch from your copy of v.3.5.0, instead of main. The v.3.5.0 branch will only have bug fixes and no new features. And then we can make another PR from there to main, or just manually copy those changes to main, depending on how difficult the merge conflict resolutions are.

**Comment by mahimatics** [comment]
> Also, I'm not sure how we will backport this commit to the v3.5 branch. Should I make a separate PR to merge to that branch?

No, I don't think that's required. As far as the open API docs are concerned, we usually just point everyone to the [live version](https://authorization.iudx.org.in/apis) anyway. So as long as that is updated, it's fine.

But if there are changes / bug fixes that need to be backported to v.3.5.0, then you can just make that PR to that branch from your copy of v.3.5.0, instead of main. The v.3.5.0 branch will only have bug fixes and no new features. And then we can make another PR from there to main, or just manually copy those changes to main, depending on how difficult the merge conflict resolutions are.

**Comment by ThorodanBrom** [comment]
I think we would need to push these changes to the v3.5 branch also. The webpage displayed in the `/apis` endpoint is rendered using the `docs/openapi.yaml` file in the git repository.

**Pull request merged**
