### PR TITLE
Stop writing realm roles back to Keycloak on user profile creation/updation and provider approval

### PR DESCRIPTION
**Pull request by ThorodanBrom**
- We can now lower privileges of the `keycloak-admin` client that is configured during set up

### CODE REVIEW

**Comment by ThorodanBrom** [comment]
Have lowered the privileges for `keycloak-admin` in the integration test realm to only have `query-users`, `view-realms`. Let's see if tests pass

**Comment by abhi4578** [comment]
tests might fail because in master u have done flyway migration and both branches uses same postgres db? @ThorodanBrom

**Comment by ThorodanBrom** [comment]
> tests might fail because in master u have done flyway migration and both branches uses same postgres db? @ThorodanBrom

Yes, you're right. Will create a new schema containing the old data, config would need to be updated then

**Comment by ThorodanBrom** [comment]
Have only added `view-users` privilege to the `keycloak-admin` client

**Comment by ThorodanBrom** [comment]
- Failing tests are due to the cat API update
- Seems like only `view-users` role/privilege is required

**Review by abhi4578 — APPROVED** [review]

**Pull request merged**
