### PR TITLE
Adding default apiserver ports

### PR DESCRIPTION
**Pull request by abhi4578**
- default http port is 8080,
- Added configurable httpPort option in config

### CODE REVIEW

**Comment by abhi4578** [comment]
ok to test

**Comment by ThorodanBrom** [comment]
I've added some changes in this PR -> https://github.com/abhi4578/iudx-aaa-server-1/pull/1

If possible, could we either:
- Remove all references to port 8443 in the configs and the README and change everything to 8080. We can then add detail in the config that if a port change is desired, add the `httpPort` key to the config.
- Make the default port 8443 itself, instead of 8080

The problem I see now is that the README will have to be worded as below (it's a little confusing to me):

> The server will be running at 8443, as per the supplied config-dev/config-depl/config-test (`httpPort`). The default port is 8080 when no port is specified in the config.

If this us OK to you, or you can reword it better, then we can leave it as is.

**Comment by abhi4578** [comment]
> I've added some changes in this PR -> https://github.com/abhi4578/iudx-aaa-server-1/pull/1
> If possible, could we either:
> 
>     * Remove all references to port 8443 in the configs and the README and change everything to 8080. We can then add detail in the config that if a port change is desired, add the `httpPort` key to the config.
This option sounds good. we can go ahead with this.. In all other apiservers we have the httpPort at 8080 and hence this pr was raised to make it uniform and also to make it configurable if desired.

**Comment by ThorodanBrom** [comment]
> > I've added some changes in this PR -> [abhi4578#1](https://github.com/abhi4578/iudx-aaa-server-1/pull/1)
> > If possible, could we either:
> > ```
> > * Remove all references to port 8443 in the configs and the README and change everything to 8080. We can then add detail in the config that if a port change is desired, add the `httpPort` key to the config.
> > ```
> 
> This option sounds good. we can go ahead with this.. In all other apiservers we have the default http server port at 8080 and hence this pr was raised to make it uniform and also to make it configurable if change is desired.
> 
> Thanks! @ThorodanBrom

OK if @mahimatics approves, I'll make the changes to the README and configs. I'll add the the `httpPort` key only in `configs/config-example.json` and refer to that in the README.

**Comment by mahimatics** [comment]
> > > I've added some changes in this PR -> [abhi4578#1](https://github.com/abhi4578/iudx-aaa-server-1/pull/1)
> > > If possible, could we either:
> > > ```
> > > * Remove all references to port 8443 in the configs and the README and change everything to 8080. We can then add detail in the config that if a port change is desired, add the `httpPort` key to the config.
> > > ```
> > 
> > 
> > This option sounds good. we can go ahead with this.. In all other apiservers we have the default http server port at 8080 and hence this pr was raised to make it uniform and also to make it configurable if change is desired.
> > Thanks! @ThorodanBrom
> 
> OK if @mahimatics approves, I'll make the changes to the README and configs. I'll add the the `httpPort` key only in `configs/config-example.json` and refer to that in the README.

Sounds good to me. You can add those commits to this PR. It'll be better to have the `httpPort` as a configurable value.

**Comment by ThorodanBrom** [comment]
Made the changes here -> https://github.com/abhi4578/iudx-aaa-server-1/pull/1/commits/292847f1feac4f81da669b33c07a0885a78683db

**Comment by abhi4578** [comment]
> Made the changes here -> [abhi4578@292847f](https://github.com/abhi4578/iudx-aaa-server-1/commit/292847f1feac4f81da669b33c07a0885a78683db).
> 
> @abhi4578 you can decide whether the docker compose files need to have 8443.

Merged the changes from [abhi4578@292847f](https://github.com/abhi4578/iudx-aaa-server-1/commit/292847f1feac4f81da669b33c07a0885a78683db). to this pR

- Have removed port 8443 from compose files . But it has some implications :
- two implications:
   -  the integration test  postman env needs to be changed to 8080
at jenkins ci, for integration test to work
   -  All other existing prs need to merge this PR . Let me know @ThorodanBrom  if thats okay.

**Comment by abhi4578** [comment]
chuck it :) . will keep 8443 only for integration tests and it should not affect other prs

**Comment by ThorodanBrom** [comment]
Yeah, let us just add `httpPort:8443` to the integration test config.

**Comment by abhi4578** [comment]
done. ready to be tested and be merged.

**Comment by ThorodanBrom** [comment]
[54da345](https://github.com/datakaveri/iudx-aaa-server/pull/151/commits/54da345768fad65b647c8ac5c0638c4c9a49d0c2) - this is not our integration test config, it's used in the unit tests. The integration test config is not currently part of the repo.

**Comment by abhi4578** [comment]
> [54da345](https://github.com/datakaveri/iudx-aaa-server/pull/151/commits/54da345768fad65b647c8ac5c0638c4c9a49d0c2) - this is not our integration test config, it's used in the unit tests. The integration test config is not currently part of the repo.

okay, its done at jenkins. will revert this commit.

**Comment by ThorodanBrom** [comment]
> > [54da345](https://github.com/datakaveri/iudx-aaa-server/pull/151/commits/54da345768fad65b647c8ac5c0638c4c9a49d0c2) - this is not our integration test config, it's used in the unit tests. The integration test config is not currently part of the repo.
> 
> okay, its done at jenkins. will revert this commit?
 Yeah, I think it's best to revert it

**Comment by abhi4578** [comment]
> > > [54da345](https://github.com/datakaveri/iudx-aaa-server/pull/151/commits/54da345768fad65b647c8ac5c0638c4c9a49d0c2) - this is not our integration test config, it's used in the unit tests. The integration test config is not currently part of the repo.
> > 
> > 
> > okay, its done at jenkins. will revert this commit?
> 
> Yeah, I think it's best to revert it
cool. done. no problem.

**Review by ThorodanBrom — APPROVED** [review]

**Comment by ThorodanBrom** [comment]
retest this please

**Review by mahimatics — APPROVED** [review]

**Pull request merged**
