### PR TITLE
Code Formatting and SAST Integration

### PR DESCRIPTION
**Pull request by ThorodanBrom**
This PR will contain commits related to adding code formatting, Checkstyle and PMD into the workflow.

## eba0d7b - Include Checkstyle in Maven validate phase
- Checkstyle runs checks on code before compilation now
- Checkstyle will fail if errors/warnings count increases beyond
current limit
- Once all existing violations are removed, the count will also
be removed
- Update `google_checks.xml` to latest version

------

## TODO
- Note, many checks, around 1000 get fixed by Spotless
- Fix as many checks as we can

### CODE REVIEW

**Comment by ThorodanBrom** [comment]
## 3dc2558 - Enabled Spotless Plugin with google code style style

- Delete outdated eclipse google style config

- Spotless plugin formats code according to google style
- Ratcheting enabled
	- Only modified files will be checked
	- This is to avoid a big commit that formats all code at once
------
- We can choose to have a big commit to format all code at once, though

**Comment by ThorodanBrom** [comment]
## e91d731 - Added PMD plugin to run at validate phase
- Added count check for now
- Excluded design ruleset
-----

## Problems with PMD
- There were no adequate 3rd party rule sets by OWASP or any other reputable source
- [The security ruleset is very subpar](https://pmd.sourceforge.io/pmd-6.53.0/pmd_rules_java_security.html)
    - There are only 2 rules and both deal w/ cryptography 
- The design ruleset has been excluded 
    - It has nice checks like cyclomatic complexity, but unhelpful ones like the law of demeter one
-----

## TODO
- Go through all rules, select a good set and use that 
- Work to fixing as many violations as we can

----
## Current rule violations w/ count

```
      1 ConsecutiveAppendsShouldReuse
      1 ConstructorCallsOverridableMethod
      1 EmptyCatchBlock
      1 ImplicitSwitchFallThrough
      1 SwitchStmtsShouldHaveDefault
      1 SystemPrintln
      2 PositionLiteralsFirstInCaseInsensitiveComparisons
      3 ForLoopCanBeForeach
      3 InvalidLogMessageFormat
      3 InvalidSlf4jMessageFormat
      3 LiteralsFirstInComparisons
      3 NullAssignment
      3 StringToString
      4 AvoidLiteralsInIfCondition
      5 AvoidPrintStackTrace
      5 UnusedLocalVariable
      6 RedundantFieldInitializer
      7 AssignmentToNonFinalStatic
      7 UnnecessaryCaseChange
      7 UnusedPrivateField
     11 AvoidInstantiatingObjectsInLoops
     13 AvoidFieldNameMatchingMethodName
     15 AvoidDuplicateLiterals
     16 UnusedAssignment
     22 UseCollectionIsEmpty
     41 UseLocaleWithCaseConversions
     49 UnusedImports
    158 GuardLogStatement
    249 DataflowAnomalyAnalysis

```

**Comment by ThorodanBrom** [comment]
## d1670d8 - Added SpotBugs + FindSecurityBugs after compile phase
- SpotBugs and FindSecurityBugs was recommended in the OSSF static analysis section along with PMD

**Comment by ThorodanBrom** [comment]
## https://github.com/datakaveri/iudx-aaa-server/pull/274/commits/0a22e5cc0a3e3f96a95b1f3aa12d56d5ff546a06 - Removed Spotless Plugin
- Formatting of code might be done by a GitHub action instead

## https://github.com/datakaveri/iudx-aaa-server/pull/274/commits/56b5558f7823ba2d789d07b8d18c08c00bbe5c57 - Make SAST tools not run by default
- We can configure them to run in the test script instead (running them manually makes a simple `mvn compile` tedious)

**Comment by ThorodanBrom** [comment]
## https://github.com/datakaveri/iudx-aaa-server/pull/274/commits/ba6860d16dfc0e980ac4669e29d52cf02dbc9db8 - Update Jenkinsfile to display Checkstyle, PMD, spotbugs reports
- The Jenkins build 306 has the reports as part of the Jenkins UI - https://jenkins.iudx.io/job/iudx%20aaa-server%20(PR)%20pipeline/306/

**Review by karun-singh — APPROVED** [review]
LGTM

**Pull request merged**
