### PR TITLE
Test cases add for ListPolicyNotification, UpdateListPolicyNotif and VerifyPolicy

### PR DESCRIPTION
**Pull request by ankitmashu**
1. in POM,Excluded VertxEBProxy from Jacoco.
2. Improved Coverage for Policy Package by adding test cases in ListPolicyNotification , UpdateListPolicyNotification and VerifyPolicyTest

### CODE REVIEW

**Comment by ThorodanBrom** [comment]
ok to test

**Comment by ThorodanBrom** [comment]
retest this please

**Comment by mahimatics** [comment]
retest this please

**Comment by ankitmashu** [comment]
Test cases for Verify Policy merged and For list notif and update notif, are work under progress

**Pull request closed without merging**
