### PR TITLE
Change openjdk base image in Dockerfile due to depreciation

### PR DESCRIPTION
**Pull request by tharak1242**

### CODE REVIEW

**Comment by abhi4578** [comment]
ok to test

**Comment by abhi4578** [comment]
retest this please

**Comment by abhi4578** [comment]
@tharak1242 mention why this fix is done in commit message

**Comment by abhi4578** [comment]
- Updated openjdk, maven docker image with eclipse-temurin
- The openjdk image is officially deprecated - https://hub.docker.com/_/openjdk
- Hence, migrated base image to Eclipse-temurin - https://hub.docker.com/_/eclipse-temurin, maintained by https://github.com/adoptium/containers

**Review by ThorodanBrom — APPROVED** [review]

**Pull request merged**
