### PR TITLE
Updates for new dependencies

### PR DESCRIPTION
**Pull request by ThorodanBrom**
Updates made for Keycloak 18.0.2, PostgreSQL 14.4
- 22abbf605e7b22e4b35b13c71f38718c73f106e1 : POM updates for updated Keycloak version
- 20a733d1913aca0c6ce5dcd713922deb0b616e3c : Updates for PostgreSQL 14.4 for flyway, SCRAM password auth
-  dbe38a346f21952ad2f770636fd8012eb09aeeff : Update PgConnectOptions with keep alive, and reconnection options

### CODE REVIEW

**Comment by ThorodanBrom** [comment]
The pipeline should fail, since both unit and integration tests are based on old Keycloak and old PostgreSQL

**Review by abhi4578 — COMMENTED** [review]
Looks good for rest, tcp keepalive can be remove at client  as its now enabled at server itself.

**Comment by ThorodanBrom** [comment]
Have removed the keep-alive config in https://github.com/datakaveri/iudx-aaa-server/pull/196/commits/6d052f88d0d24be008abd17b6b85d0035eed2121. Testing Vert.x 4.3.2 in https://github.com/datakaveri/iudx-aaa-server/pull/196/commits/905e1eb95975e4d4a399fb9baa04432c3a6ea02f

**Comment by karun-singh** [comment]
retest this please

**Comment by karun-singh** [comment]
retest this please

**Pull request merged**
