### PR TITLE
[4.5.0] Updated apidoc.html spec-url

### PR DESCRIPTION
**Pull request by karun-singh**
- Updated API docs spec-url to work with nginx cos changes.

### CODE REVIEW

**Comment by karun-singh** [comment]
retest this please

**Comment by ThorodanBrom** [comment]
retest this please

**Comment by ThorodanBrom** [comment]
The Flyway migration for integration test data is happening twice - once with V9 and then again with V1000. V1000 should only be there in the main pipeline, so not sure what's going wrong

**Comment by abhi4578** [comment]
retest this please

**Comment by abhi4578** [comment]
> The Flyway migration for integration test data is happening twice - once with V9 and then again with V1000. V1000 should only be there in the main pipeline, so not sure what's going wrong

its not getting deleted properly, after that stage - https://github.com/datakaveri/iudx-aaa-server/blob/4b661d73840eec7852fdf6cf910973d2c028d801/Jenkinsfile#L74 , should be mostly ``src/main/resources/db/migration/V?*__Add_Integration_Test_data.sql`` 

for now i have deleted it manually, but still giving, surprisingly zap proxy

**Comment by ThorodanBrom** [comment]
retest this please

**Comment by ThorodanBrom** [comment]
Not sure, need to see the Postman report or the logs

**Comment by karun-singh** [comment]
> > The Flyway migration for integration test data is happening twice - once with V9 and then again with V1000. V1000 should only be there in the main pipeline, so not sure what's going wrong
> 
> its not getting deleted properly, after that stage -
> 
> https://github.com/datakaveri/iudx-aaa-server/blob/4b661d73840eec7852fdf6cf910973d2c028d801/Jenkinsfile#L74
> , should be mostly `src/main/resources/db/migration/V?*__Add_Integration_Test_data.sql` @karun-singh ?
> 
> for now i have deleted it manually, but still giving errors surprisingly zap proxy

From the latest execution, it looks like it is deleting the file as expected. It only needs to match a single character since the version is single digit only as of now. So having `V?__Add_Integration_Test_data.sql` is perfectly fine.

**Comment by karun-singh** [comment]
> Not sure, need to see the Postman report or the logs

Okay, will extract logs of the container during integration testing.

**Comment by karun-singh** [comment]
retest this please

**Comment by abhi4578** [comment]
> > > The Flyway migration for integration test data is happening twice - once with V9 and then again with V1000. V1000 should only be there in the main pipeline, so not sure what's going wrong
> > 
> > 
> > its not getting deleted properly, after that stage -
> > https://github.com/datakaveri/iudx-aaa-server/blob/4b661d73840eec7852fdf6cf910973d2c028d801/Jenkinsfile#L74
> > 
> > , should be mostly `src/main/resources/db/migration/V?*__Add_Integration_Test_data.sql` @karun-singh ?
> > for now i have deleted it manually, but still giving errors surprisingly zap proxy
> 
> From the latest execution, it looks like it is deleting the file as expected. It only needs to match a single character since the version is single digit only as of now. So having `V?__Add_Integration_Test_data.sql` is perfectly fine.

In main its 100, https://github.com/datakaveri/iudx-aaa-server/blob/main/docker/runIntegTests.sh#L4, you can just hard code that file to be removed also

**Comment by karun-singh** [comment]
> > > > The Flyway migration for integration test data is happening twice - once with V9 and then again with V1000. V1000 should only be there in the main pipeline, so not sure what's going wrong
> > > 
> > > 
> > > its not getting deleted properly, after that stage -
> > > https://github.com/datakaveri/iudx-aaa-server/blob/4b661d73840eec7852fdf6cf910973d2c028d801/Jenkinsfile#L74
> > > 
> > > , should be mostly `src/main/resources/db/migration/V?*__Add_Integration_Test_data.sql` @karun-singh ?
> > > for now i have deleted it manually, but still giving errors surprisingly zap proxy
> > 
> > 
> > From the latest execution, it looks like it is deleting the file as expected. It only needs to match a single character since the version is single digit only as of now. So having `V?__Add_Integration_Test_data.sql` is perfectly fine.
> 
> In main its 1000, [`main`/docker/runIntegTests.sh#L4](https://github.com/datakaveri/iudx-aaa-server/blob/main/docker/runIntegTests.sh?rgh-link-date=2023-06-28T04%3A44%3A53Z#L4),

Right, the main branch has v1000 but there the copy is not dynamically assigning the version based on the number of files already present in the directory like it is doing here. So it'll always be 1000, and the file will be overwritten by the copy command on each execution so doesn't really need cleaning.

**Comment by karun-singh** [comment]
retest this please

**Comment by karun-singh** [comment]
Will recreate once other fixes are merged.

**Comment by karun-singh** [comment]
> > > > > The Flyway migration for integration test data is happening twice - once with V9 and then again with V1000. V1000 should only be there in the main pipeline, so not sure what's going wrong
> > > > 
> > > > 
> > > > its not getting deleted properly, after that stage -
> > > > https://github.com/datakaveri/iudx-aaa-server/blob/4b661d73840eec7852fdf6cf910973d2c028d801/Jenkinsfile#L74
> > > > 
> > > > , should be mostly `src/main/resources/db/migration/V?*__Add_Integration_Test_data.sql` @karun-singh ?
> > > > for now i have deleted it manually, but still giving errors surprisingly zap proxy
> > > 
> > > 
> > > From the latest execution, it looks like it is deleting the file as expected. It only needs to match a single character since the version is single digit only as of now. So having `V?__Add_Integration_Test_data.sql` is perfectly fine.
> > 
> > 
> > In main its 1000, [`main`/docker/runIntegTests.sh#L4](https://github.com/datakaveri/iudx-aaa-server/blob/main/docker/runIntegTests.sh?rgh-link-date=2023-06-28T04%3A57%3A37Z#L4),
> 
> Right, the main branch has v1000 but there the copy is not dynamically assigning the version based on the number of files already present in the directory like it is doing here. So it'll always be 1000, and the file will be overwritten by the copy command on each execution so doesn't really need cleaning.

@abhi4578 Okay, got it. In the PR pipeline, both main and 4.5.0 branches are executed so there the V1000 file will not be cleaned and subsequent 4.5.0 pipeline execution will fail. 
Will modify the pattern matching in the main pipeline's cleanup commands.

**Pull request closed without merging**
