### PR TITLE
Added test cases for Delete Notification API

### PR DESCRIPTION
**Pull request by code-akki**
Updated the test suit with-
  * State of notification is not pending.
  * Id is invalid.
  * A successful completion of API calling.
  * A successful completion of API calling with multiple ids.

### CODE REVIEW

**Comment by MohammedAman23** [comment]
ok to test

**Comment by mahimatics** [comment]
retest this please

**Comment by karun-singh** [comment]
Aborted the build as it will go on indefinitely. Please pull commit [4a87511](https://github.com/datakaveri/iudx-aaa-server/commit/4a8751165c8614eeb8cc5fe4e13c52acf9a1bb15) from the `main` branch into this PR branch for the fix.

**Comment by karun-singh** [comment]
retest this please

**Pull request merged**
