### PR TITLE
Catalogue client refactor 

### PR DESCRIPTION
**Pull request by MohammedAman23**
added ResourceObj class  and updated checkReqItem method in CatalogueClient class to have resource detail in the response map
moved resource server detail from catalogueClient to create policy
added ComposeException class and updated reponse in createPolicy and verifyPolicy
added unit tests for create policy and verify policy
updated unit tests for URN changes

### CODE REVIEW

**Comment by ThorodanBrom** [comment]
Please test this

**Comment by ThorodanBrom** [comment]
OK to test

**Comment by karun-singh** [comment]
test this please

**Comment by karun-singh** [comment]
ok to test

**Pull request merged**
